// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZbxAgent_PushValue_FullMethodName  = "/agent.ZbxAgent/pushValue"
	ZbxAgent_PushValues_FullMethodName = "/agent.ZbxAgent/pushValues"
)

// ZbxAgentClient is the client API for ZbxAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZbxAgentClient interface {
	PushValue(ctx context.Context, in *ZbxValue, opts ...grpc.CallOption) (*ZbxValueAck, error)
	PushValues(ctx context.Context, in *ListZbxValue, opts ...grpc.CallOption) (*ZbxValueAck, error)
}

type zbxAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewZbxAgentClient(cc grpc.ClientConnInterface) ZbxAgentClient {
	return &zbxAgentClient{cc}
}

func (c *zbxAgentClient) PushValue(ctx context.Context, in *ZbxValue, opts ...grpc.CallOption) (*ZbxValueAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZbxValueAck)
	err := c.cc.Invoke(ctx, ZbxAgent_PushValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zbxAgentClient) PushValues(ctx context.Context, in *ListZbxValue, opts ...grpc.CallOption) (*ZbxValueAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZbxValueAck)
	err := c.cc.Invoke(ctx, ZbxAgent_PushValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZbxAgentServer is the server API for ZbxAgent service.
// All implementations must embed UnimplementedZbxAgentServer
// for forward compatibility.
type ZbxAgentServer interface {
	PushValue(context.Context, *ZbxValue) (*ZbxValueAck, error)
	PushValues(context.Context, *ListZbxValue) (*ZbxValueAck, error)
	mustEmbedUnimplementedZbxAgentServer()
}

// UnimplementedZbxAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZbxAgentServer struct{}

func (UnimplementedZbxAgentServer) PushValue(context.Context, *ZbxValue) (*ZbxValueAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushValue not implemented")
}
func (UnimplementedZbxAgentServer) PushValues(context.Context, *ListZbxValue) (*ZbxValueAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushValues not implemented")
}
func (UnimplementedZbxAgentServer) mustEmbedUnimplementedZbxAgentServer() {}
func (UnimplementedZbxAgentServer) testEmbeddedByValue()                  {}

// UnsafeZbxAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZbxAgentServer will
// result in compilation errors.
type UnsafeZbxAgentServer interface {
	mustEmbedUnimplementedZbxAgentServer()
}

func RegisterZbxAgentServer(s grpc.ServiceRegistrar, srv ZbxAgentServer) {
	// If the following call pancis, it indicates UnimplementedZbxAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZbxAgent_ServiceDesc, srv)
}

func _ZbxAgent_PushValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZbxValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZbxAgentServer).PushValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZbxAgent_PushValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZbxAgentServer).PushValue(ctx, req.(*ZbxValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZbxAgent_PushValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZbxValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZbxAgentServer).PushValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZbxAgent_PushValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZbxAgentServer).PushValues(ctx, req.(*ListZbxValue))
	}
	return interceptor(ctx, in, info, handler)
}

// ZbxAgent_ServiceDesc is the grpc.ServiceDesc for ZbxAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZbxAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.ZbxAgent",
	HandlerType: (*ZbxAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "pushValue",
			Handler:    _ZbxAgent_PushValue_Handler,
		},
		{
			MethodName: "pushValues",
			Handler:    _ZbxAgent_PushValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
