// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: zbxgrpc.proto

package zbxgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZbxSender_PushValue_FullMethodName  = "/zbxgrpc.ZbxSender/pushValue"
	ZbxSender_PushValues_FullMethodName = "/zbxgrpc.ZbxSender/pushValues"
)

// ZbxSenderClient is the client API for ZbxSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZbxSenderClient interface {
	PushValue(ctx context.Context, in *ZbxValue, opts ...grpc.CallOption) (*ZbxValueAck, error)
	PushValues(ctx context.Context, in *ListZbxValue, opts ...grpc.CallOption) (*ZbxValueAck, error)
}

type zbxSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewZbxSenderClient(cc grpc.ClientConnInterface) ZbxSenderClient {
	return &zbxSenderClient{cc}
}

func (c *zbxSenderClient) PushValue(ctx context.Context, in *ZbxValue, opts ...grpc.CallOption) (*ZbxValueAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZbxValueAck)
	err := c.cc.Invoke(ctx, ZbxSender_PushValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zbxSenderClient) PushValues(ctx context.Context, in *ListZbxValue, opts ...grpc.CallOption) (*ZbxValueAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZbxValueAck)
	err := c.cc.Invoke(ctx, ZbxSender_PushValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZbxSenderServer is the server API for ZbxSender service.
// All implementations must embed UnimplementedZbxSenderServer
// for forward compatibility.
type ZbxSenderServer interface {
	PushValue(context.Context, *ZbxValue) (*ZbxValueAck, error)
	PushValues(context.Context, *ListZbxValue) (*ZbxValueAck, error)
	mustEmbedUnimplementedZbxSenderServer()
}

// UnimplementedZbxSenderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZbxSenderServer struct{}

func (UnimplementedZbxSenderServer) PushValue(context.Context, *ZbxValue) (*ZbxValueAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushValue not implemented")
}
func (UnimplementedZbxSenderServer) PushValues(context.Context, *ListZbxValue) (*ZbxValueAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushValues not implemented")
}
func (UnimplementedZbxSenderServer) mustEmbedUnimplementedZbxSenderServer() {}
func (UnimplementedZbxSenderServer) testEmbeddedByValue()                   {}

// UnsafeZbxSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZbxSenderServer will
// result in compilation errors.
type UnsafeZbxSenderServer interface {
	mustEmbedUnimplementedZbxSenderServer()
}

func RegisterZbxSenderServer(s grpc.ServiceRegistrar, srv ZbxSenderServer) {
	// If the following call pancis, it indicates UnimplementedZbxSenderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZbxSender_ServiceDesc, srv)
}

func _ZbxSender_PushValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZbxValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZbxSenderServer).PushValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZbxSender_PushValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZbxSenderServer).PushValue(ctx, req.(*ZbxValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZbxSender_PushValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZbxValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZbxSenderServer).PushValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZbxSender_PushValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZbxSenderServer).PushValues(ctx, req.(*ListZbxValue))
	}
	return interceptor(ctx, in, info, handler)
}

// ZbxSender_ServiceDesc is the grpc.ServiceDesc for ZbxSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZbxSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zbxgrpc.ZbxSender",
	HandlerType: (*ZbxSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "pushValue",
			Handler:    _ZbxSender_PushValue_Handler,
		},
		{
			MethodName: "pushValues",
			Handler:    _ZbxSender_PushValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zbxgrpc.proto",
}
